package com.jjrapps.constanza.scheduling

import android.app.AlarmManager
import android.app.PendingIntent
import android.content.Context
import android.content.Intent
import com.jjrapps.constanza.core.time.TimeProvider
import com.jjrapps.constanza.core.time.millisUntilNextLocalTime
import com.jjrapps.constanza.core.time.nextLocalDateForLocalTime
import com.jjrapps.constanza.reminding.DayReviewSettingsStore
import dagger.hilt.android.qualifiers.ApplicationContext
import javax.inject.Inject

/**
 * day-review-exact-alarm: a SECOND, independent `PendingIntent` request-code scheme, exactly the
 * reasoning [com.jjrapps.constanza.reminding.DayReviewNotificationPoster]'s own
 * `DAY_REVIEW_NOTIFICATION_ID = -1` documents. [AlarmScheduler] already documents `occurrenceId` as
 * the request code for every per-habit alarm, and that id is always a positive `Long` — Room's
 * autogenerated primary key never assigns zero or negative (SQLite `rowid` autoincrement starts at
 * 1). The day review has no `reminder_occurrences` row at all: it reviews the whole day, not one
 * occurrence, so it cannot borrow that scheme. A fixed negative constant is chosen for the identical
 * reason `DayReviewNotificationPoster` picked one: it can never collide with any `occurrenceId.toInt()`
 * value that scheme will ever produce.
 */
private const val DAY_REVIEW_ALARM_REQUEST_CODE = -1

/**
 * day-review-exact-alarm: arms the next "review your day" nudge as an exact `AlarmManager` alarm
 * instead of `WorkManager` one-time work. design.md:1158 (habit-tracking-mvp, task 4a's Doze
 * measurement) recorded `AlarmScheduler`'s own exact-alarm path surviving Doze on this project's
 * device matrix ("With `mState=IDLE`, the alarm fired, `ReminderFireWorker` ran, notification
 * posted") — `WorkManager` one-time work has no equivalent guarantee against a wall-clock target,
 * which is exactly why the nightly review could previously slip past midnight under Doze deferral
 * and be silently suppressed by [DayReviewFireWorker]'s own late-fire guard once the midnight sweep
 * had already rewritten the day.
 *
 * Deliberately its own class rather than a second method on [AlarmScheduler]: that class's public
 * surface is keyed on `occurrenceId` end to end ([AlarmScheduler.cancel], its `pendingIntentFor`),
 * and the day review has no such id (see [DAY_REVIEW_ALARM_REQUEST_CODE]'s own KDoc). Both classes
 * share the one exact/inexact decision through [scheduleExactOrInexact] (see that function's KDoc),
 * so "which API survives Doze" still lives in exactly one place even though the id schemes differ.
 */
class DayReviewAlarmScheduler @Inject constructor(
    private val alarmManager: AlarmManager,
    @ApplicationContext private val context: Context,
    private val timeProvider: TimeProvider,
    private val settingsStore: DayReviewSettingsStore,
) {
    /**
     * Arms the next review at [DayReviewSettingsStore.currentReviewTimeMinuteOfDay], reusing
     * [TimeProvider.millisUntilNextLocalTime]/[TimeProvider.nextLocalDateForLocalTime] exactly as
     * [WorkScheduler]'s own now-deleted `scheduleDayReview` did — the DST-sensitive resolution stays
     * in [TimeProvider] and is never re-derived here. The target LOCAL DATE
     * ([TimeProvider.nextLocalDateForLocalTime]) rides along as [DayReviewFireReceiver.EXTRA_SCHEDULED_DATE]
     * so [DayReviewFireWorker]'s late-fire guard can compare it against [TimeProvider.today] at fire
     * time, the same contract [DayReviewFireWorker] documents.
     *
     * Called from every one of [RescheduleReceivers]'s trigger receivers (boot, package replace,
     * time change, exact-alarm grant) in addition to [DayReviewFireWorker] re-arming its own
     * successor — `AlarmManager` alarms, unlike `WorkManager` requests, do not survive a reboot or a
     * package replace, so this call is this feature's only source of truth after any of those.
     */
    suspend fun scheduleNext() {
        val minuteOfDay = settingsStore.currentReviewTimeMinuteOfDay()
        val targetDate = timeProvider.nextLocalDateForLocalTime(minuteOfDay)
        val atEpochMilli = timeProvider.now().toEpochMilli() + timeProvider.millisUntilNextLocalTime(minuteOfDay)
        val intent = Intent(context, DayReviewFireReceiver::class.java)
        intent.putExtra(DayReviewFireReceiver.EXTRA_SCHEDULED_DATE, targetDate.toString())
        val pendingIntent = PendingIntent.getBroadcast(
            context,
            DAY_REVIEW_ALARM_REQUEST_CODE,
            intent,
            PendingIntent.FLAG_IMMUTABLE or PendingIntent.FLAG_UPDATE_CURRENT,
        )
        alarmManager.scheduleExactOrInexact(pendingIntent, atEpochMilli)
    }
}
