package com.jjrapps.constanza.reminding

import android.annotation.SuppressLint
import android.app.Notification
import android.app.NotificationChannel
import android.app.NotificationManager
import android.app.PendingIntent
import android.content.Context
import androidx.core.app.NotificationCompat
import androidx.core.app.NotificationManagerCompat
import com.jjrapps.constanza.R
import com.jjrapps.constanza.localization.AppLocaleController
import dagger.hilt.android.qualifiers.ApplicationContext
import javax.inject.Inject

private const val DAY_REVIEW_CHANNEL_ID = "day_review"

/**
 * day-review, slice B (day-review-notification): the second, and only other, notification channel
 * this app posts to. Deliberately never `"reminders"` ([NotificationPoster]'s channel, private in
 * that file) — the owner must be able to mute the once-a-night day-review nudge from system
 * settings without muting the per-habit reminders that actually carry the answer actions, and a
 * shared channel would make that impossible.
 */
private const val DAY_REVIEW_NOTIFICATION_ID = -1

/**
 * day-review, slice B: posts the once-a-night "review your day" notification —
 * [DayReviewNotificationPoster] is the only class that does, mirroring [NotificationPoster]'s own
 * "posted, and only ever posted, through this class" rule, one class per channel.
 *
 * A deliberately separate class from [NotificationPoster], not a parameterised extra branch on
 * [NotificationPoster.buildNotification]: that function hardcodes three [NotificationCompat.Action]s
 * and a per-habit [NotificationCompat.Builder.setColor] tint, both asserted by
 * [com.jjrapps.constanza.reminding.NotificationPosterInstrumentedTest] against exactly that shape.
 * A review has no habit, no colour, and no per-slot action to offer — it can only ever say "go
 * look" — so parameterising the reminder builder to also cover this shape would either weaken those
 * assertions or force this notification to carry machinery (actions, a colour) that means nothing
 * for it.
 *
 * [DAY_REVIEW_NOTIFICATION_ID] is a SECOND, independent notification-id scheme. [NotificationPoster]
 * documents `occurrenceId` as "the same integer [AlarmScheduler] already uses" and states there is
 * "no second id scheme anywhere in this pipeline" — true for every per-habit reminder, because every
 * one of those is backed by a real `reminder_occurrences` row whose Room-autogenerated primary key
 * is always a positive `Long` (SQLite `rowid` autoincrement starts at 1 and never assigns zero or
 * negative). A day-review notification has no such row — it reviews the whole day, not one
 * occurrence — so it cannot borrow that scheme; a fixed negative constant is chosen specifically
 * because it can never collide with any `occurrenceId.toInt()` value that scheme will ever produce.
 */
class DayReviewNotificationPoster @Inject constructor(
    @ApplicationContext private val context: Context,
    private val appLocaleController: AppLocaleController,
) {
    private val manager = NotificationManagerCompat.from(context)

    /** Mirrors [NotificationPoster.postReminder]'s contract exactly: `false` means [canPost] gated
     *  the post and nothing reached the system, `true` means it did. [outstandingCount] is
     *  [com.jjrapps.constanza.tracking.DayReviewDecision.Post]'s own count — this class never
     *  recomputes it, only renders it. */
    suspend fun postReview(outstandingCount: Int): Boolean {
        val localizedContext = appLocaleController.localizedApplicationContext()
        if (!canPost(localizedContext)) return false
        postToSystem(buildNotification(localizedContext, outstandingCount))
        return true
    }

    /** See [NotificationPoster.postToSystem]'s identical KDoc for why this is named `postToSystem`
     *  and why the `@SuppressLint` is scoped this narrowly. */
    @SuppressLint("MissingPermission")
    private fun postToSystem(notification: Notification) {
        manager.notify(DAY_REVIEW_NOTIFICATION_ID, notification)
    }

    /** [NotificationPoster.canPost]'s identical degradation rule, re-read on every call rather than
     *  cached, for the identical reason: a muted channel is never a silent lie about delivery. */
    fun canPost(): Boolean = canPost(context)

    private fun canPost(ctx: Context): Boolean {
        ensureChannel(ctx)
        if (!manager.areNotificationsEnabled()) return false
        val importance = manager.getNotificationChannel(DAY_REVIEW_CHANNEL_ID)?.importance
            ?: NotificationManager.IMPORTANCE_DEFAULT
        return importance != NotificationManager.IMPORTANCE_NONE
    }

    /** `IMPORTANCE_DEFAULT`, not `IMPORTANCE_HIGH` ([NotificationPoster]'s reminder channel): a
     *  reminder is time-sensitive — missing it can mean missing the habit's own window entirely —
     *  while the day-review nudge is a once-a-night summary the owner can act on any time before the
     *  midnight sweep. `IMPORTANCE_HIGH` earns a heads-up peek/sound for every post; a nightly nudge
     *  intruding that way is closer to nagging than to a useful reminder, and `IMPORTANCE_DEFAULT`
     *  still shows in the shade and can post a sound, just without the heads-up interruption. */
    private fun ensureChannel(ctx: Context) {
        manager.createNotificationChannel(
            NotificationChannel(
                DAY_REVIEW_CHANNEL_ID,
                ctx.getString(R.string.notification_channel_day_review_name),
                NotificationManager.IMPORTANCE_DEFAULT,
            ),
        )
    }

    /** No [NotificationCompat.Builder.addAction] and no [NotificationCompat.Builder.setColor] — see
     *  the class KDoc for why. [outstandingCount] decides which of two fixed strings the body reads:
     *  zero renders the "all answered" copy regardless of [ReminderSettingsStore]/mode, since
     *  [com.jjrapps.constanza.tracking.decideDayReview] only ever calls [postReview] with zero when
     *  fires-every-night is on — the only-when-pending mode never posts at zero at all. */
    private fun buildNotification(ctx: Context, outstandingCount: Int): Notification {
        val text = if (outstandingCount > 0) {
            ctx.resources.getQuantityString(
                R.plurals.notification_day_review_outstanding,
                outstandingCount,
                outstandingCount,
            )
        } else {
            ctx.getString(R.string.notification_day_review_all_done)
        }
        return NotificationCompat.Builder(ctx, DAY_REVIEW_CHANNEL_ID)
            .setSmallIcon(R.drawable.ic_notification_reminder)
            .setContentTitle(ctx.getString(R.string.notification_day_review_title))
            .setContentText(text)
            .setStyle(NotificationCompat.BigTextStyle().bigText(text))
            .setPriority(NotificationCompat.PRIORITY_DEFAULT)
            .setAutoCancel(true)
            .setContentIntent(contentIntent(ctx))
            .build()
    }

    /**
     * reminder-notification-tap-opens-today's [reminderTapIntent] is reused verbatim, not
     * reimplemented: reading [com.jjrapps.constanza.core.ui.MainActivity.onNewIntent] shows the
     * extra it sets ([com.jjrapps.constanza.core.ui.MainActivity.EXTRA_FROM_REMINDER_NOTIFICATION])
     * drives nothing reminder-specific — it only tells `onNewIntent` "a notification body was
     * tapped, land on Today and reset navigation to the live edge", carrying no occurrence id or
     * other per-reminder data. That is exactly "tapping opens Today", generically, which is exactly
     * what this notification needs too. The constant's name says "reminder" for historical reasons
     * (it predates this second caller), not because its effect is reminder-only; renaming it is out
     * of scope for this change and would touch [NotificationPoster]'s own call site for no behaviour
     * change.
     *
     * [DAY_REVIEW_NOTIFICATION_ID] doubles as this `PendingIntent`'s request code, exactly as
     * [NotificationPoster.contentIntent] reuses `occurrenceId` for its own — different factory
     * ([PendingIntent.getActivity], never `getBroadcast`) and a request-code space that can never
     * collide with `occurrenceId.toInt()` (see the class KDoc), so this stays a distinct system
     * entry from every reminder `PendingIntent` on both grounds [NotificationPoster] already relies
     * on for its own four.
     */
    private fun contentIntent(ctx: Context): PendingIntent =
        PendingIntent.getActivity(
            ctx,
            DAY_REVIEW_NOTIFICATION_ID,
            reminderTapIntent(ctx),
            PendingIntent.FLAG_IMMUTABLE or PendingIntent.FLAG_UPDATE_CURRENT,
        )
}
