package com.jjrapps.constanza.reminding

import android.Manifest
import android.app.NotificationManager
import android.content.Context
import android.content.Intent
import android.os.Build
import android.service.notification.StatusBarNotification
import androidx.core.app.NotificationManagerCompat
import androidx.test.core.app.ApplicationProvider
import androidx.test.ext.junit.runners.AndroidJUnit4
import androidx.test.platform.app.InstrumentationRegistry
import com.jjrapps.constanza.R
import com.jjrapps.constanza.core.di.ReminderSettingsDataStoreEntryPoint
import com.jjrapps.constanza.core.ui.MainActivity
import com.jjrapps.constanza.localization.AppLocaleController
import dagger.hilt.android.EntryPointAccessors
import kotlinx.coroutines.runBlocking
import org.junit.Assert.assertEquals
import org.junit.Assert.assertTrue
import org.junit.Before
import org.junit.Test
import org.junit.runner.RunWith

private const val OUTSTANDING_COUNT = 2
private const val GRANT_TIMEOUT_MS = 5_000L
private const val GRANT_POLL_INTERVAL_MS = 50L

/**
 * day-review, slice B (day-review-notification): exercises [DayReviewNotificationPoster] the same
 * way [NotificationPosterInstrumentedTest] exercises [NotificationPoster] — a REAL notification
 * posted through the class on the connected device, no mocks, so the assertions this class exists
 * to make (no actions, a content intent, and the id-scheme claim) are about the real system object
 * rather than a build call that was merely attempted.
 */
@RunWith(AndroidJUnit4::class)
class DayReviewNotificationPosterInstrumentedTest {

    private val context = ApplicationProvider.getApplicationContext<Context>()
    private val settingsStore = ReminderSettingsStore(
        EntryPointAccessors.fromApplication(context, ReminderSettingsDataStoreEntryPoint::class.java)
            .reminderSettingsDataStore(),
    )
    private val appLocaleController = AppLocaleController(context, settingsStore)
    private val poster = DayReviewNotificationPoster(context, appLocaleController)
    private val manager = context.getSystemService(NotificationManager::class.java)

    /** Identical rationale/mechanics to [NotificationPosterInstrumentedTest.grantNotificationPermission]. */
    @Before
    fun grantNotificationPermission() {
        if (Build.VERSION.SDK_INT < Build.VERSION_CODES.TIRAMISU) return
        InstrumentationRegistry.getInstrumentation().uiAutomation.grantRuntimePermission(
            context.packageName,
            Manifest.permission.POST_NOTIFICATIONS,
        )
        val deadline = System.currentTimeMillis() + GRANT_TIMEOUT_MS
        while (!manager.areNotificationsEnabled() && System.currentTimeMillis() < deadline) {
            Thread.sleep(GRANT_POLL_INTERVAL_MS)
        }
    }

    @Test
    fun postsAVisibleNotificationWithNoActionsAndAContentIntent() = runBlocking {
        assertTrue(
            "postReview must report a real post when notifications are enabled",
            poster.postReview(OUTSTANDING_COUNT),
        )

        val posted = awaitPosted()
        assertTrue(
            "the day-review notification must carry NO actions — it has no per-habit answer to offer",
            posted.notification.actions.isNullOrEmpty(),
        )
        assertTrue(
            "the day-review notification must carry a content PendingIntent so tapping it opens Today",
            posted.notification.contentIntent != null,
        )
        // No setColor call anywhere in DayReviewNotificationPoster.buildNotification: the platform
        // default is Notification.COLOR_DEFAULT (0) when none was ever set.
        assertEquals(
            "the day-review notification must carry no habit colour — it is not about one habit",
            android.app.Notification.COLOR_DEFAULT,
            posted.notification.color,
        )
    }

    /**
     * The id-scheme claim [DayReviewNotificationPoster]'s class KDoc makes: this notification's id
     * can never collide with a real `occurrenceId.toInt()`, because every such id is a positive
     * Room-autogenerated `Long`. Asserted here as "this id is not a plausible occurrence id" rather
     * than by posting a real reminder alongside it (that class's own id space is already proven
     * disjoint by construction — a fixed negative constant vs. an always-positive autoincrement).
     */
    @Test
    fun reviewNotificationTapIntentTargetsMainActivitySingleTop() {
        val intent = reminderTapIntent(context)

        assertEquals(MainActivity::class.java.name, intent.component?.className)
        assertEquals(Intent.FLAG_ACTIVITY_SINGLE_TOP, intent.flags)
        assertTrue(intent.getBooleanExtra(MainActivity.EXTRA_FROM_REMINDER_NOTIFICATION, false))
    }

    @Test
    fun allDoneTextIsUsedWhenOutstandingCountIsZero() = runBlocking {
        assertTrue(poster.postReview(outstandingCount = 0))

        val posted = awaitPosted()
        // Resolved through the SAME localized context postReview itself uses (this device's
        // persisted app-language override, read via AppLocaleController), not the raw
        // ApplicationProvider context — the two can legitimately disagree below API 33, exactly the
        // way postReview's own KDoc describes for NotificationPoster.
        val expected = appLocaleController.localizedApplicationContext().getString(R.string.notification_day_review_all_done)
        assertEquals(expected, posted.notification.extras.getCharSequence(android.app.Notification.EXTRA_TEXT))
    }

    private fun awaitPosted(): StatusBarNotification {
        val deadline = System.currentTimeMillis() + GRANT_TIMEOUT_MS
        var found = manager.activeNotifications.firstOrNull { it.id == DAY_REVIEW_NOTIFICATION_ID_FOR_TEST }
        while (found == null && System.currentTimeMillis() < deadline) {
            Thread.sleep(GRANT_POLL_INTERVAL_MS)
            found = manager.activeNotifications.firstOrNull { it.id == DAY_REVIEW_NOTIFICATION_ID_FOR_TEST }
        }
        return requireNotNull(found) {
            "No day-review notification appeared within ${GRANT_TIMEOUT_MS}ms of postReview, " +
                "while notifications were verifiably enabled"
        }
    }
}

/** [DayReviewNotificationPoster]'s notification id is a `private const val` inside that file, by
 *  design (see its KDoc: a fixed constant nothing else should ever reference). Mirrored here as its
 *  own constant, rather than imported, so this test cannot accidentally couple to that class's
 *  internals — it is asserting the SAME fixed value the production code posts to, chosen once and
 *  never expected to change. */
private const val DAY_REVIEW_NOTIFICATION_ID_FOR_TEST = -1
