"""Per-scene navigation for Constanza's Play Store screenshots.

Scene order and numbering follow docs/play-store-publication-texts.md's "Capturas — Orden
recomendado" table exactly — 1 Today, 2 notification, 3 habit editor, 4 colour picker, 5 habit
list, 6 settings, 7 progress. Progress sits last deliberately: it is real, honest UI (three lines
of text, nothing to fake), not a hero shot, so it does not compete for the two above-the-fold slots
Play shows without scrolling.

Every scene function that ends mid-navigation returns the app to a KNOWN screen before the next
one starts — usually by relaunching outright (`force_stop` + `start_app`) rather than trusting a
chain of back presses. That is not caution for its own sake: a full pass measured live that a
single back press from Progress exits straight past Today to the launcher, and a single back press
from Settings does too — the back stack this app builds when a screen is reached through Habit
List's overflow menu does not shrink one level at a time the way it looks like it should.
"""

from __future__ import annotations

import json
import time
from dataclasses import dataclass
from pathlib import Path

import ui

STRINGS = {
    "es": {
        "today_title": "Hoy",
        "settings": "Ajustes",
        "manage_habits": "Hábitos",
        "more_options": "Más opciones",
        "progress_menu": "Progreso",
        "schedule_label": "Frecuencia",
        "schedule_daily": "Diaria",
        "schedule_monthly": "Mensual",
        "color_label": "Color",
        "color_more": "Más",
        "notification_snooze": "Aplazar",
        "notification_title": "Buenos hábitos",
        # Section headers are rendered upper-cased by SettingsSection's own composable
        # (`.uppercase()`), never the string resource's own mixed case — confirmed live: scrolling
        # for the resource's exact casing looped through all 8 attempts while the upper-cased text
        # sat on screen the whole time, unscrolled.
        "portability_section": "DATOS Y COPIA DE SEGURIDAD",
        "day_review_section": "REPASO DEL DÍA",
        "progress_title": "Progreso",
        "habit_list_title": "Hábitos",
        "habit_editor_title": "Editar hábito",
        "target_habit": "Leer 20 minutos",
        "discard_confirm": "Descartar",
    },
    "en": {
        "today_title": "Today",
        "settings": "Settings",
        "manage_habits": "Habits",
        "more_options": "More options",
        "progress_menu": "Progress",
        "schedule_label": "Frequency",
        "schedule_daily": "Daily",
        "schedule_monthly": "Monthly",
        "color_label": "Colour",
        "color_more": "More",
        "notification_snooze": "Snooze",
        "notification_title": "Good habits",
        "portability_section": "DATA & BACKUP",
        "day_review_section": "DAY REVIEW",
        "progress_title": "Progress",
        "habit_list_title": "Habits",
        "habit_editor_title": "Edit habit",
        "target_habit": "Read 20 minutes",
        "discard_confirm": "Discard",
    },
}

# Order matters: it is both the capture order and the Play Store listing order (T1 doc,
# docs/play-store-publication-texts.md, generated by scripts/generar-textos-ficha.py).
SCENES = [
    "01-hoy",
    "02-notificacion",
    "03-editor-habito",
    "04-selector-color",
    "05-lista-habitos",
    "06-ajustes",
    "07-progreso",
]

SETTLE_SECONDS = 0.6  # a short, fixed pause AFTER a text-based wait already succeeded, for the
# one frame of recomposition/ripple animation Compose can still be mid-way through — never used
# as a substitute for wait_for_text itself.

NOTIFICATION_WAIT_SECONDS = 240  # SEED_LEAD_MINUTES=2 in ListingScreenshotSeed.kt, plus headroom
# for a slow emulator and for AlarmManager's own dispatch jitter.


@dataclass
class SceneResult:
    scene: str
    path: Path
    notes: dict


def _settle() -> None:
    time.sleep(SETTLE_SECONDS)


def _return_to_today(serial: str, lang: str) -> None:
    """The one navigation primitive every multi-step scene below falls back to instead of chained
    back presses — see the module's own docstring for the measured back-stack surprises that made
    this the reliable choice. A cold relaunch always opens on Today: the seed leaves onboarding
    marked done, and the real system POST_NOTIFICATIONS permission was already granted before the
    pipeline started."""
    ui.force_stop(serial)
    ui.start_app(serial)
    ui.wait_for_text(serial, STRINGS[lang]["today_title"])


def capture_today(serial: str, lang: str, out: Path) -> SceneResult:
    s = STRINGS[lang]
    # Before the first shot, not only before the notification scene: every foreign notification
    # also puts an icon in the status bar, which demo mode does not hide on this API level.
    ui.clear_all_notifications(serial)
    ui.wait_for_text(serial, s["today_title"])
    _settle()
    ui.screenshot(serial, out)
    return SceneResult("today", out, {})


def capture_notification(serial: str, lang: str, out: Path) -> SceneResult:
    s = STRINGS[lang]
    ui.clear_all_notifications(serial)
    ui.demo_notification_icons(serial, visible=True)
    ui.wait_for_own_notification(serial, timeout=NOTIFICATION_WAIT_SECONDS)
    _open_shade_on_own_notification(serial, s)
    own, total = ui.notification_counts(serial)  # one shared dump — see its own KDoc for why

    # The DEVICE's system locale, not Constanza's own per-app override, governs the shade's own
    # chrome ("Clear all", the quick-settings peek row) — this is the exact scene that can catch a
    # leaked system locale that `cmd locale set-app-locales` cannot fake past, since the app's own
    # notification text sits right next to that chrome in the same screenshot. Fails the batch
    # immediately, loudly, rather than only being caught later by revisar.py's own manifest check.
    leak = ui.system_locale_leak(serial, lang)
    if leak is not None:
        raise RuntimeError(
            f"System-locale leak in the {lang} notification scene: found '{leak}', which belongs to "
            f"the OTHER language. The device's system_locales setting did not take effect — see "
            f"ui.set_system_locale_and_reboot's own KDoc."
        )

    ui.screenshot(serial, out)
    ui.collapse_shade(serial)
    ui.demo_notification_icons(serial, visible=False)
    return SceneResult(
        "notification", out, {"own_notifications": own, "total_notifications": total, "system_locale_leak": leak},
    )


def _shade_is_open(serial: str) -> bool:
    focus = ui.shell(serial, "dumpsys", "window", check=False)
    return any("mCurrentFocus" in line and "NotificationShade" in line for line in focus.splitlines())


def _open_shade_on_own_notification(serial: str, s: dict) -> None:
    """Opens the shade and proves it is open before the shot. The first full run took scene 02
    with the shade already collapsed again — the text wait had passed, the screenshot showed
    Today. So this waits for the reminder's own "Snooze" action (only ever drawn inside the
    shade, never in the app) and then checks the focused window is the shade itself, re-opening
    once if it is not.

    `expand-notifications`, not `expand-settings`, is already the correct command — its own
    documented behaviour is "open the notifications panel" versus "...and expand quick settings if
    present" — and a raw swipe gesture produces an identical result. The small quick-settings tile
    row (Wi-Fi/Bluetooth/Mobile data/Quick Share) that still appears above the notification is this
    Android version's own standard single-pull shade chrome, not the FULL quick-settings grid
    `expand-settings` would add (brightness slider, many more tiles) — measured directly against
    both commands and against swipes of varying length, all four produced the same tile row, and no
    adb-accessible flag was found that suppresses it."""
    for _ in range(2):
        ui.expand_shade(serial)
        ui.wait_for_text(serial, s["notification_title"])
        ui.wait_for_text(serial, s["notification_snooze"])
        _settle()
        if _shade_is_open(serial):
            return
    raise ui.UiTimeout("the notification shade would not stay open")


def _open_target_habit_editor(serial: str, lang: str) -> None:
    """Today -> Habit list -> tap the target habit's OWN row (not the add-habit affordance): the
    row itself is the edit entry point (`HabitRow`'s `Modifier.clickable { onEditHabit(habit.id) }`
    in HabitListScreen.kt), so this opens the EXISTING, already-filled habit — name, notes, colour
    and schedule all populated — rather than a blank "New habit" form."""
    s = STRINGS[lang]
    ui.tap_text(serial, s["manage_habits"])
    ui.wait_for_text(serial, s["habit_list_title"])
    ui.tap_text(serial, s["target_habit"])
    ui.wait_for_text(serial, s["habit_editor_title"])


def capture_habit_editor(serial: str, lang: str, out: Path) -> SceneResult:
    s = STRINGS[lang]
    _open_target_habit_editor(serial, lang)
    # Tap the field by its current VALUE ("Daily"), not by the "Frequency" heading above it:
    # the heading is plain text, and the first run tapped it, opened nothing, and still passed a
    # wait for "Daily" — which is the closed field's own value. "Monthly" only exists in the menu.
    ui.tap_text(serial, s["schedule_daily"])
    ui.wait_for_text(serial, s["schedule_monthly"])
    _settle()
    ui.screenshot(serial, out)
    return SceneResult("habit_editor", out, {})


def capture_color_picker(serial: str, lang: str, out: Path) -> SceneResult:
    s = STRINGS[lang]
    # Dismiss the still-open schedule dropdown by RE-TAPPING its own already-selected item
    # ("Daily"), not by tapping "Colour": while a Compose DropdownMenu's Popup is showing,
    # `uiautomator dump` only returns THAT popup window's own accessibility tree — every node from
    # the screen underneath, "Colour" included, is simply absent from the dump, not merely
    # obscured, so waiting for it there always times out. The popup's own item list, on the other
    # hand, is exactly what the dump DOES contain, and "Daily" is already one of its rows (the
    # current selection), so tapping it re-confirms the same value and closes the menu — a
    # text-located dismissal, never a raw coordinate. Not back: a back press closed the whole
    # editor outright in the first full run, not just the dropdown.
    ui.tap_text(serial, s["schedule_daily"])
    ui.wait_absent(serial, s["schedule_monthly"])
    ui.tap_text(serial, s["color_more"])
    _settle()
    ui.screenshot(serial, out)
    # Leave the editor without saving: press back, dismiss a "discard changes?" dialog if the app
    # actually considers anything dirty (re-selecting the same schedule value and merely expanding
    # the colour grid may not count as a change at all), then relaunch outright rather than trust
    # wherever "back" actually lands — see the module docstring.
    ui.press_back(serial)
    try:
        ui.tap_text(serial, s["discard_confirm"], timeout=5)
    except ui.UiTimeout:
        pass
    _return_to_today(serial, lang)
    return SceneResult("color_picker", out, {})


def capture_habit_list(serial: str, lang: str, out: Path) -> SceneResult:
    s = STRINGS[lang]
    ui.tap_text(serial, s["manage_habits"])
    ui.wait_for_text(serial, s["habit_list_title"])
    _settle()
    ui.screenshot(serial, out)
    _return_to_today(serial, lang)
    return SceneResult("habit_list", out, {})


def capture_settings(serial: str, lang: str, out: Path) -> SceneResult:
    s = STRINGS[lang]
    ui.tap_text(serial, s["settings"])
    # Deliberately NO scroll at all: measured directly that Snooze + Data & backup + Language +
    # Day review together are simply too tall to fit one phone-format screen with every heading
    # intact and nothing orphaned — scrolling to bring Day Review's own heading near the top always
    # pushed Snooze's tail ("2 h / 3 h / 4 h", with no heading above it) into frame instead, and the
    # content does not fit at any scroll position in between either (tried an anchored scroll to
    # the exact pixel and small-step iterative correction; the far end of the list simply does not
    # reach the top of the frame while the near end is still on screen). The unscrolled top —
    # Snooze fully shown, then Data & backup, then Language, cut off before Day Review even starts
    # rather than mid-way through it — is the one framing that shows every visible heading intact
    # with nothing orphaned above the fold, which is what a Play Store screenshot needs most.
    _settle()
    ui.screenshot(serial, out)
    return SceneResult("settings", out, {})


def capture_progress(serial: str, lang: str, out: Path) -> SceneResult:
    s = STRINGS[lang]
    ui.tap_text(serial, s["manage_habits"])
    ui.wait_for_text(serial, s["habit_list_title"])
    ui.tap_nearest(serial, s["target_habit"], s["more_options"])
    ui.tap_text(serial, s["progress_menu"])
    # ProgressScreen's own top bar shows the HABIT'S NAME, not the literal "Progress" string —
    # `state.habitName.ifEmpty { stringResource(progress_title) }`, and habitName is never empty
    # here — so that is what this waits for, not s["progress_title"].
    ui.wait_for_text(serial, s["target_habit"])
    _settle()
    ui.screenshot(serial, out)
    return SceneResult("progress", out, {})


def capture_all(serial: str, lang: str, out_dir: Path) -> list[SceneResult]:
    """Captures the full ordered scene set into out_dir/01-hoy.png .. 07-progreso.png, returning a
    per-scene manifest entry revisar.py cross-checks (notification counts and the system-locale
    leak flag in particular, since neither can be recovered from the finished PNG alone)."""
    results: list[SceneResult] = []
    results.append(capture_today(serial, lang, out_dir / f"{SCENES[0]}.png"))
    results.append(capture_notification(serial, lang, out_dir / f"{SCENES[1]}.png"))
    results.append(capture_habit_editor(serial, lang, out_dir / f"{SCENES[2]}.png"))
    results.append(capture_color_picker(serial, lang, out_dir / f"{SCENES[3]}.png"))
    results.append(capture_habit_list(serial, lang, out_dir / f"{SCENES[4]}.png"))
    results.append(capture_settings(serial, lang, out_dir / f"{SCENES[5]}.png"))
    _return_to_today(serial, lang)
    results.append(capture_progress(serial, lang, out_dir / f"{SCENES[6]}.png"))
    return results


def write_manifest_entries(manifest_path: Path, lang: str, formato: str, results: list[SceneResult]) -> None:
    manifest: dict = {}
    if manifest_path.exists():
        manifest = json.loads(manifest_path.read_text())
    manifest.setdefault(lang, {})[formato] = {
        r.scene: {"path": str(r.path.relative_to(manifest_path.parent)), **r.notes} for r in results
    }
    manifest_path.write_text(json.dumps(manifest, indent=2, ensure_ascii=False, sort_keys=True))
